import 'package:magic_hands/moduls/food_info.dart';

class BeefData {
  static List<FoodInfo> foodList = [
    FoodInfo(
        "Beef and Mustard Pie",
        "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
        "52874",
        "Unknown",
        0),
    FoodInfo(
        "Beef and Oyster pie",
        "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
        "52878",
        "Unknown",
        0),
    FoodInfo(
        "Beef Asado",
        "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
        "53071",
        "Unknown",
        0),
    FoodInfo(
        "Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber",
        "https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg",
        "52997",
        "Unknown",
        0),
    FoodInfo(
        "Beef Bourguignon",
        "https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg",
        "52904",
        "Unknown",
        0),
    FoodInfo(
        "Beef Brisket Pot Roast",
        "https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg",
        "52812",
        "Unknown",
        0),
    FoodInfo(
        "Beef Caldereta",
        "https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg",
        "53070",
        "Unknown",
        0),
    FoodInfo(
        "Beef Dumpling Stew",
        "https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg",
        "52873",
        "Unknown",
        0),
    FoodInfo(
        "Beef Lo Mein",
        "https://www.themealdb.com/images/media/meals/1529444830.jpg",
        "52952",
        "Unknown",
        0),
    FoodInfo(
        "Beef Mechado",
        "https://www.themealdb.com/images/media/meals/cgl60b1683206581.jpg",
        "53068",
        "Unknown",
        0),
    FoodInfo(
        "Beef Rendang",
        "https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg",
        "53053",
        "Unknown",
        0),
    FoodInfo(
        "Beef stroganoff",
        "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
        "52834",
        "Unknown",
        0),
    FoodInfo(
        "Beef Sunday Roast",
        "https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg",
        "52824",
        "Unknown",
        0),
    FoodInfo(
        "Beef Wellington",
        "https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg",
        "52803",
        "Unknown",
        0),
    FoodInfo(
        "Big Mac",
        "https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg",
        "53013",
        "Unknown",
        0),
    FoodInfo(
        "Bistek",
        "https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg",
        "53069",
        "Unknown",
        0),
    FoodInfo(
        "Bitterballen (Dutch meatballs)",
        "https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg",
        "52979",
        "Unknown",
        0),
    FoodInfo(
        "Braised Beef Chilli",
        "https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg",
        "52826",
        "Unknown",
        0),
    FoodInfo(
        "Cevapi Sausages",
        "https://www.themealdb.com/images/media/meals/vc08jn1628769553.jpg",
        "53055",
        "Unknown",
        0),
    FoodInfo(
        "Chivito uruguayo",
        "https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg",
        "53063",
        "Unknown",
        0),
    FoodInfo(
        "Corned Beef and Cabbage",
        "https://www.themealdb.com/images/media/meals/xb97a81583266727.jpg",
        "52998",
        "Unknown",
        0),
    FoodInfo(
        "Croatian Bean Stew",
        "https://www.themealdb.com/images/media/meals/tnwy8m1628770384.jpg",
        "53058",
        "Unknown",
        0),
    FoodInfo(
        "Croatian lamb peka",
        "https://www.themealdb.com/images/media/meals/pn59o51628769837.jpg",
        "53056",
        "Unknown",
        0),
    FoodInfo(
        "Egyptian Fatteh",
        "https://www.themealdb.com/images/media/meals/rlwcc51598734603.jpg",
        "53031",
        "Unknown",
        0),
    FoodInfo(
        "Gołąbki (cabbage roll)",
        "https://www.themealdb.com/images/media/meals/q8sp3j1593349686.jpg",
        "53021",
        "Unknown",
        0),
    FoodInfo(
        "Irish stew",
        "https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg",
        "52781",
        "Unknown",
        0),
    FoodInfo(
        "Jamaican Beef Patties",
        "https://www.themealdb.com/images/media/meals/wsqqsw1515364068.jpg",
        "52938",
        "Unknown",
        0),
    FoodInfo(
        "Ma Po Tofu",
        "https://www.themealdb.com/images/media/meals/1525874812.jpg",
        "52947",
        "Unknown",
        0),
    FoodInfo(
        "Massaman Beef curry",
        "https://www.themealdb.com/images/media/meals/tvttqv1504640475.jpg",
        "52827",
        "Unknown",
        0),
    FoodInfo(
        "Minced Beef Pie",
        "https://www.themealdb.com/images/media/meals/xwutvy1511555540.jpg",
        "52876",
        "Unknown",
        0),
    FoodInfo(
        "Montreal Smoked Meat",
        "https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg",
        "52927",
        "Unknown",
        0),
    FoodInfo(
        "Moussaka",
        "https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg",
        "53006",
        "Unknown",
        0),
    FoodInfo(
        "Mulukhiyah",
        "https://www.themealdb.com/images/media/meals/x372ug1598733932.jpg",
        "53029",
        "Unknown",
        0),
    FoodInfo(
        "Oxtail with broad beans",
        "https://www.themealdb.com/images/media/meals/1520083578.jpg",
        "52943",
        "Unknown",
        0),
    FoodInfo(
        "Paszteciki (Polish Pasties)",
        "https://www.themealdb.com/images/media/meals/c9a3l31593261890.jpg",
        "53017",
        "Unknown",
        0),
    FoodInfo(
        "Pate Chinois",
        "https://www.themealdb.com/images/media/meals/yyrrxr1511816289.jpg",
        "52930",
        "Unknown",
        0),
    FoodInfo(
        "Portuguese prego with green piri-piri",
        "https://www.themealdb.com/images/media/meals/ewcikl1614348364.jpg",
        "53042",
        "Unknown",
        0),
    FoodInfo(
        "Red Peas Soup",
        "https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg",
        "52941",
        "Unknown",
        0),
    FoodInfo(
        "Roti john",
        "https://www.themealdb.com/images/media/meals/hx335q1619789561.jpg",
        "53052",
        "Unknown",
        0),
    FoodInfo(
        "Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots",
        "https://www.themealdb.com/images/media/meals/o2wb6p1581005243.jpg",
        "52992",
        "Unknown",
        0),
    FoodInfo(
        "Spaghetti Bolognese",
        "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
        "52770",
        "Unknown",
        0),
    FoodInfo(
        "Steak and Kidney Pie",
        "https://www.themealdb.com/images/media/meals/qysyss1511558054.jpg",
        "52881",
        "Unknown",
        0),
    FoodInfo(
        "Steak Diane",
        "https://www.themealdb.com/images/media/meals/vussxq1511882648.jpg",
        "52935",
        "Unknown",
        0),
    FoodInfo(
        "Szechuan Beef",
        "https://www.themealdb.com/images/media/meals/1529443236.jpg",
        "52950",
        "Unknown",
        0),
    FoodInfo(
        "Traditional Croatian Goulash",
        "https://www.themealdb.com/images/media/meals/n1hcou1628770088.jpg",
        "53057",
        "Unknown",
        0),
    FoodInfo(
        "Vegetable Shepherd's Pie",
        "https://www.themealdb.com/images/media/meals/w8umt11583268117.jpg",
        "53000",
        "Unknown",
        0),
  ];
}
