import 'package:magic_hands/moduls/food_info.dart';

class ChickenData {
  static List<FoodInfo> foodList = [
    FoodInfo(
        "15-minute chicken & halloumi burgers",
        "https://www.themealdb.com/images/media/meals/vdwloy1713225718.jpg",
        "53085",
        "",
        0),
    FoodInfo(
        "Ayam Percik",
        "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
        "53050",
        "",
        0),
    FoodInfo(
        "Brown Stew Chicken",
        "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
        "52940",
        "",
        0),
    FoodInfo(
        "Chick-Fil-A Sandwich",
        "https://www.themealdb.com/images/media/meals/sbx7n71587673021.jpg",
        "53016",
        "",
        0),
    FoodInfo(
        "Chicken & mushroom Hotpot",
        "https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg",
        "52846",
        "",
        0),
    FoodInfo(
        "Chicken Alfredo Primavera",
        "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
        "52796",
        "",
        0),
    FoodInfo(
        "Chicken Basquaise",
        "https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg",
        "52934",
        "",
        0),
    FoodInfo(
        "Chicken Congee",
        "https://www.themealdb.com/images/media/meals/1529446352.jpg",
        "52956",
        "",
        0),
    FoodInfo(
        "Chicken Couscous",
        "https://www.themealdb.com/images/media/meals/qxytrx1511304021.jpg",
        "52850",
        "",
        0),
    FoodInfo(
        "Chicken Enchilada Casserole",
        "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
        "52765",
        "",
        0),
    FoodInfo(
        "Chicken Fajita Mac and Cheese",
        "https://www.themealdb.com/images/media/meals/qrqywr1503066605.jpg",
        "52818",
        "",
        0),
    FoodInfo(
        "Chicken Ham and Leek Pie",
        "https://www.themealdb.com/images/media/meals/xrrtss1511555269.jpg",
        "52875",
        "",
        0),
    FoodInfo(
        "Chicken Handi",
        "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
        "52795",
        "",
        0),
    FoodInfo(
        "Chicken Karaage",
        "https://www.themealdb.com/images/media/meals/tyywsw1505930373.jpg",
        "52831",
        "",
        0),
    FoodInfo(
        "Chicken Marengo",
        "https://www.themealdb.com/images/media/meals/qpxvuq1511798906.jpg",
        "52920",
        "",
        0),
    FoodInfo(
        "Chicken Parmentier",
        "https://www.themealdb.com/images/media/meals/uwvxpv1511557015.jpg",
        "52879",
        "",
        0),
    FoodInfo(
        "Chicken Quinoa Greek Salad",
        "https://www.themealdb.com/images/media/meals/k29viq1585565980.jpg",
        "53011",
        "",
        0),
    FoodInfo(
        "Coq au vin",
        "https://www.themealdb.com/images/media/meals/qstyvs1505931190.jpg",
        "52832",
        "",
        0),
    FoodInfo(
        "Crock Pot Chicken Baked Tacos",
        "https://www.themealdb.com/images/media/meals/ypxvwv1505333929.jpg",
        "52830",
        "",
        0),
    FoodInfo(
        "French Onion Chicken with Roasted Carrots & Mashed Potatoes",
        "https://www.themealdb.com/images/media/meals/b5ft861583188991.jpg",
        "52996",
        "",
        0),
    FoodInfo(
        "General Tso's Chicken",
        "https://www.themealdb.com/images/media/meals/1529444113.jpg",
        "52951",
        "",
        0),
    FoodInfo(
        "Honey Balsamic Chicken with Crispy Broccoli & Potatoes",
        "https://www.themealdb.com/images/media/meals/kvbotn1581012881.jpg",
        "52993",
        "",
        0),
    FoodInfo(
        "Jerk chicken with rice & peas",
        "https://www.themealdb.com/images/media/meals/tytyxu1515363282.jpg",
        "52937",
        "",
        0),
    FoodInfo(
        "Katsu Chicken curry",
        "https://www.themealdb.com/images/media/meals/vwrpps1503068729.jpg",
        "52820",
        "",
        0),
    FoodInfo(
        "Kentucky Fried Chicken",
        "https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg",
        "52813",
        "",
        0),
    FoodInfo(
        "Kung Pao Chicken",
        "https://www.themealdb.com/images/media/meals/1525872624.jpg",
        "52945",
        "",
        0),
    FoodInfo(
        "Nutty Chicken Curry",
        "https://www.themealdb.com/images/media/meals/yxsurp1511304301.jpg",
        "52851",
        "",
        0),
    FoodInfo(
        "Pad See Ew",
        "https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg",
        "52774",
        "",
        0),
    FoodInfo(
        "Piri-piri chicken and slaw",
        "https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg",
        "53039",
        "",
        0),
    FoodInfo(
        "Potato Gratin with Chicken",
        "https://www.themealdb.com/images/media/meals/qwrtut1468418027.jpg",
        "52780",
        "",
        0),
    FoodInfo(
        "Rappie Pie",
        "https://www.themealdb.com/images/media/meals/ruwpww1511817242.jpg",
        "52933",
        "",
        0),
    FoodInfo(
        "Rosół (Polish Chicken Soup)",
        "https://www.themealdb.com/images/media/meals/lx1kkj1593349302.jpg",
        "53020",
        "",
        0),
    FoodInfo(
        "Shawarma",
        "https://www.themealdb.com/images/media/meals/kcv6hj1598733479.jpg",
        "53028",
        "",
        0),
    FoodInfo(
        "Tandoori chicken",
        "https://www.themealdb.com/images/media/meals/qptpvt1487339892.jpg",
        "52806",
        "",
        0),
    FoodInfo(
        "Teriyaki Chicken Casserole",
        "https://www.themealdb.com/images/media/meals/wvpsxx1468256321.jpg",
        "52772",
        "",
        0),
    FoodInfo(
        "Thai Green Curry",
        "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
        "52814",
        "",
        0)
  ];
}
