import 'package:magic_hands/moduls/food_info.dart';

class VegetarianData {
  static List<FoodInfo> foodList = [
    FoodInfo(
        "Baingan Bharta",
        "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
        "52807",
        "",
        0),
    FoodInfo(
        "Beetroot Soup (Borscht)",
        "https://www.themealdb.com/images/media/meals/zadvgb1699012544.jpg",
        "53078",
        "",
        0),
    FoodInfo(
        "Cabbage Soup (Shchi)",
        "https://www.themealdb.com/images/media/meals/60oc3k1699009846.jpg",
        "53077",
        "",
        0),
    FoodInfo(
        "Chickpea Fajitas",
        "https://www.themealdb.com/images/media/meals/tvtxpq1511464705.jpg",
        "52870",
        "",
        0),
    FoodInfo(
        "Crispy Eggplant",
        "https://www.themealdb.com/images/media/meals/c7lzrl1683208757.jpg",
        "53072",
        "",
        0),
    FoodInfo(
        "Dal fry",
        "https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg",
        "52785",
        "",
        0),
    FoodInfo(
        "Egg Drop Soup",
        "https://www.themealdb.com/images/media/meals/1529446137.jpg",
        "52955",
        "",
        0),
    FoodInfo(
        "Eggplant Adobo",
        "https://www.themealdb.com/images/media/meals/y7h0lq1683208991.jpg",
        "53073",
        "",
        0),
    FoodInfo(
        "Flamiche",
        "https://www.themealdb.com/images/media/meals/wssvvs1511785879.jpg",
        "52906",
        "",
        0),
    FoodInfo(
        "Ful Medames",
        "https://www.themealdb.com/images/media/meals/lvn2d51598732465.jpg",
        "53025",
        "",
        0),
    FoodInfo(
        "Gigantes Plaki",
        "https://www.themealdb.com/images/media/meals/b79r6f1585566277.jpg",
        "53012",
        "",
        0),
    FoodInfo(
        "Grilled eggplant with coconut milk",
        "https://www.themealdb.com/images/media/meals/bopa2i1683209167.jpg",
        "53074",
        "",
        0),
    FoodInfo(
        "Kafteji",
        "https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg",
        "52971",
        "",
        0),
    FoodInfo(
        "Kidney Bean Curry",
        "https://www.themealdb.com/images/media/meals/sywrsu1511463066.jpg",
        "52868",
        "",
        0),
    FoodInfo(
        "Koshari",
        "https://www.themealdb.com/images/media/meals/4er7mj1598733193.jpg",
        "53027",
        "",
        0),
    FoodInfo(
        "Leblebi Soup",
        "https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg",
        "52973",
        "",
        0),
    FoodInfo(
        "Matar Paneer",
        "https://www.themealdb.com/images/media/meals/xxpqsy1511452222.jpg",
        "52865",
        "",
        0),
    FoodInfo(
        "Moroccan Carrot Soup",
        "https://www.themealdb.com/images/media/meals/jcr46d1614763831.jpg",
        "53047",
        "",
        0),
    FoodInfo(
        "Mushroom & Chestnut Rotolo",
        "https://www.themealdb.com/images/media/meals/ssyqwr1511451678.jpg",
        "52864",
        "",
        0),
    FoodInfo(
        "Potato Salad (Olivier Salad)",
        "https://www.themealdb.com/images/media/meals/ebvuir1699013665.jpg",
        "53081",
        "",
        0),
    FoodInfo(
        "Provençal Omelette Cake",
        "https://www.themealdb.com/images/media/meals/qwtrtp1511799242.jpg",
        "52921",
        "",
        0),
    FoodInfo(
        "Ratatouille",
        "https://www.themealdb.com/images/media/meals/wrpwuu1511786491.jpg",
        "52908",
        "",
        0),
    FoodInfo(
        "Ribollita",
        "https://www.themealdb.com/images/media/meals/xrrwpx1487347049.jpg",
        "52811",
        "",
        0),
    FoodInfo(
        "Roasted Eggplant With Tahini, Pine Nuts, and Lentils",
        "https://www.themealdb.com/images/media/meals/ysqrus1487425681.jpg",
        "52816",
        "",
        0),
    FoodInfo(
        "Shakshuka",
        "https://www.themealdb.com/images/media/meals/g373701551450225.jpg",
        "52963",
        "",
        0),
    FoodInfo(
        "Smoky Lentil Chili with Squash",
        "https://www.themealdb.com/images/media/meals/uwxqwy1483389553.jpg",
        "52784",
        "",
        0),
    FoodInfo(
        "Spanish Tortilla",
        "https://www.themealdb.com/images/media/meals/quuxsx1511476154.jpg",
        "52872",
        "",
        0),
    FoodInfo(
        "Spicy Arrabiata Penne",
        "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
        "52771",
        "",
        0),
    FoodInfo(
        "Spicy North African Potato Salad",
        "https://www.themealdb.com/images/media/meals/urtwux1486983078.jpg",
        "52797",
        "",
        0),
    FoodInfo(
        "Spinach & Ricotta Cannelloni",
        "https://www.themealdb.com/images/media/meals/wspuvp1511303478.jpg",
        "52849",
        "",
        0),
    FoodInfo(
        "Squash linguine",
        "https://www.themealdb.com/images/media/meals/wxswxy1511452625.jpg",
        "52866",
        "",
        0),
    FoodInfo(
        "Stovetop Eggplant With Harissa, Chickpeas, and Cumin Yogurt",
        "https://www.themealdb.com/images/media/meals/yqwtvu1487426027.jpg",
        "52817",
        "",
        0),
    FoodInfo(
        "Stuffed Bell Peppers with Quinoa and Black Beans",
        "https://www.themealdb.com/images/media/meals/b66myb1683207208.jpg",
        "53067",
        "",
        0),
    FoodInfo(
        "Summer Pistou",
        "https://www.themealdb.com/images/media/meals/rqtxvr1511792990.jpg",
        "52911",
        "",
        0),
    FoodInfo(
        "Tahini Lentils",
        "https://www.themealdb.com/images/media/meals/vpxyqt1511464175.jpg",
        "52869",
        "",
        0),
    FoodInfo(
        "Tamiya",
        "https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg",
        "53026",
        "",
        0),
    FoodInfo(
        "Tortang Talong",
        "https://www.themealdb.com/images/media/meals/va668f1683209318.jpg",
        "53075",
        "",
        0),
    FoodInfo(
        "Vegetarian Casserole",
        "https://www.themealdb.com/images/media/meals/vptwyt1511450962.jpg",
        "52863",
        "",
        0),
    FoodInfo(
        "Vegetarian Chilli",
        "https://www.themealdb.com/images/media/meals/wqurxy1511453156.jpg",
        "52867",
        "",
        0),
    FoodInfo(
        "Yaki Udon",
        "https://www.themealdb.com/images/media/meals/wrustq1511475474.jpg",
        "52871",
        "",
        0)
  ];
}
