name: magic_hands
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.3.0
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  http: ^1.2.2
  logger: ^2.4.0
  internet_connection_checker_plus: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.0
  

flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flags/
 
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Medium.ttf
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf

