name: magic_hands
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  go_router: ^14.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/images/
 
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Medium.ttf
    - family: BreeSerif
      fonts:
        - asset: assets/fonts/BreeSerif-Regular.ttf

